<?php

return [
    'forcePrecision2Dp'=>[
        'price',
        'shipping',
        'totalAmount',
        'taxAmount',
        'totalTaxAmount'
    ],
    'cardKeys'=>[
        'bin',
        'holder',
        'type',
        'country',
        'issuer',
        'binCountry',
        'level',
        'bank',
        'paymentBrand'
    ],
    'paymentBrandAssoc'=>[
        'VISA'=>'visa',
        'MASTER'=>'mastercard',
        'AMEX'=>'american express',
        'MAESTRO'=>'maestro'
    ],
    'address_fields' => [
        'first_name',
        'last_name',
        'company',
        'email',
        'phone',
        'address_1',
        'address_2',
        'city',
        'postcode',
        'state',
        'country'
    ],
    'oppwaLogLevels' => [
        'info' => [
            'successfully_processed'=>'/^(000\.000\.|000\.100\.1|000\.[36])/',
            'manually_reviewed'=>'/^(000\.400\.0[^3]|000\.400\.100)/',
            'pending_transactions'=>'/^(000\.200)/',
        ],
        'warning' => [
            'rejections_due_to_3dsecure_and_intercard_risk_checks'=>'/^(000\.400\.[1][0-9][1-9]|000\.400\.2)/',
            'rejections_by_the_external_bank'=>'/^(800\.[17]00|800\.800\.[123])/',
            'soft_decline'=>'/^(300\.100\.100)/',
            'rejections_due_to_external_risk_systems'=>'/^(100\.400\.[0-3]|100\.38|100\.370\.100|100\.370\.11)/',
            'rejections_due_to_blacklist_validation'=>'/^(100\.100\.701|800\.[32])/',
            'rejections_due_to_risk_validation'=>'/^(800\.1[123456]0)/',
            'rejections_due_to_risk_management'=>'/^(100\.380\.[23]|100\.380\.101)/',
            'rejections_due_to_3dsecure'=>'/^(800\.400\.2|100\.380\.4|100\.390)/',
            'rejections_due_to_registration_validation'=>'/^(100\.[13]50)/',
            'rejections_due_to_address_validation'=>'/^(800\.400\.1)/',
        ],
        'error' => [
            'error_in_asynchonous_workflow'=>'/^(100\.39[765])/',
            'rejections_due_to_reference_validation'=>'/^(700\.[1345][05]0)/',
            'rejections_due_to_address_validation'=>'/^(100\.800)/',
            'rejections_due_to_contact_validation'=>'/^(100\.[97]00)/',
            'rejections_due_to_account_validation'=>'/^(100\.100|100.2[01])/',
            'rejections_due_to_amount_validation'=>'/^(100\.55)/',
        ],
        'critical' => [
            'rejections_due_to_format_validation'=>'/^(200\.[123]|100\.[53][07]|800\.900|100\.[69]00\.500)/',
            'rejections_due_to_configuration_validation'=>'/^(600\.[23]|500\.[12]|800\.121)/',
            'rejections_due_to_job_validation'=>'/^(100\.250|100\.360)/',
        ],
        'emergency' => [
            'communication_errors'=>'/^(900\.[1234]00|000\.400\.030)/',
            'system_errors'=>'/^(800\.[56]|999\.|600\.1|800\.800\.[84])/',
        ],
    ],
    'params3dv2' => [
        'ReqAuthMethod' => 'Method used by the Cardholder to authenticate to the 3D Secure Requestor',
        'ReqAuthTimestamp' => 'Date and time in UTC of the cardholder authentication',
        'PriorAuthMethod' => 'Mechanism used by the Cardholder to previously authenticate to the 3D Secure',
        'PriorAuthTimestamp' => 'Date and time in UTC of the prior cardholder authentication',
        'AccountAgeIndicator' => 'Length of time that the cardholder has had the account with the 3D Secure Requestor',
        'AccountChangeDate' => 'Date that the cardholders account with the 3D Secure Requestor was last changed',
        'AccountChangeIndicator' => 'Length of time since the cardholders account information with the 3D Secure Requestor was last changed',
        'AccountDate' => 'Date that the cardholder opened the account with the 3D Secure Requestor YYYYMMDD',
        'AccountPasswordChangeDate' => 'Date that cardholders account with the 3D Secure Requestor had a password change',
        'AccountPasswordChangeIndicator' => 'Indicates the length of time since the cardholders account with the 3D Secure Requestor had a password change or account reset',
        'AccountPurchaseCount' => 'Number of purchases with this cardholder account during the previous six months',
        'AccountProvisioningAttempts' => 'Number of transactions (successful and abandoned) for this cardholder account with the 3D Secure Requestor across all payment accounts in the previous 24 hours',
        'AccountYearTransactions' => 'Number of transactions (successful and abandoned) for this cardholder account with the 3D Secure Requestor across all payment accounts in the previous year',
        'PaymentAccountAge' => 'Date that the payment account was enrolled in the cardholders account with the 3D Secure Requestor',
        'PaymentAccountAgeIndicator' => 'Indicates the length of time that the payment account was enrolled in the cardholders account with the 3D Secure Requestor',
        'ShipAddressUsageDate' => 'Date when the shipping address used for this transaction was first used with the 3D Secure Requestor. Accepted date format is YYYYMMDD',
        'ShipAddressUsageIndicator' => 'Indicates the length of time since the shipping address used for this transaction was first used with the 3D Secure Requestor',
        'ShipIndicator' => 'Indicates shipping method chosen for the transaction',
        'ShipNameIndicator' => 'Indicates if the Cardholder Name on the account is identical to the shipping Name used for this transaction',
        'SuspiciousAccountActivity' => 'Indicates whether the 3D Secure Requestor has experienced suspicious activity',
        'TransactionType' => 'Identifies the type of transaction being authenticated',
        'DeliveryTimeframe' => 'Indicates the merchandise delivery timeframe',
        'DeliveryEmailAddress' => 'For Electronic delivery, the email address to which the merchandise was delivered',
        'ReorderItemsIndicator' => 'Indicates whether the cardholder is reordering previously purchased merchandise'
    ],
    '3166'=> [
        'AD'=>'Andorra',
        'AE'=>'United Arab Emirates',
        'AF'=>'Afghanistan',
        'AG'=>'Antigua and Barbuda',
        'AI'=>'Anguilla',
        'AL'=>'Albania',
        'AM'=>'Armenia',
        'AO'=>'Angola',
        'AQ'=>'Antarctica',
        'AR'=>'Argentina',
        'AS'=>'American Samoa',
        'AT'=>'Austria',
        'AU'=>'Australia',
        'AW'=>'Aruba',
        'AX'=>'Aland Islands',
        'AZ'=>'Azerbaijan',
        'BA'=>'Bosnia and Herzegovina',
        'BB'=>'Barbados',
        'BD'=>'Bangladesh',
        'BE'=>'Belgium',
        'BF'=>'Burkina Faso',
        'BG'=>'Bulgaria',
        'BH'=>'Bahrain',
        'BI'=>'Burundi',
        'BJ'=>'Benin',
        'BL'=>'Saint Barthelemy',
        'BM'=>'Bermuda',
        'BN'=>'Brunei Darussalam',
        'BO'=>'Bolivia (Plurinational State of)',
        'BQ'=>'Bonaire Sint Eustatius and Saba',
        'BR'=>'Brazil',
        'BS'=>'Bahamas',
        'BT'=>'Bhutan',
        'BV'=>'Bouvet Island',
        'BW'=>'Botswana',
        'BY'=>'Belarus',
        'BZ'=>'Belize',
        'CA'=>'Canada',
        'CC'=>'Cocos (Keeling) Islands',
        'CD'=>'Congo Democratic Republic of the',
        'CF'=>'Central African Republic',
        'CG'=>'Congo',
        'CH'=>'Switzerland',
        'CI'=>'Cote dIvoire',
        'CK'=>'Cook Islands',
        'CL'=>'Chile',
        'CM'=>'Cameroon',
        'CN'=>'China',
        'CO'=>'Colombia',
        'CR'=>'Costa Rica',
        'CU'=>'Cuba',
        'CV'=>'Cabo Verde',
        'CW'=>'Curacao',
        'CX'=>'Christmas Island',
        'CY'=>'Cyprus',
        'CZ'=>'Czechia',
        'DE'=>'Germany',
        'DJ'=>'Djibouti',
        'DK'=>'Denmark',
        'DM'=>'Dominica',
        'DO'=>'Dominican Republic',
        'DZ'=>'Algeria',
        'EC'=>'Ecuador',
        'EE'=>'Estonia',
        'EG'=>'Egypt',
        'EH'=>'Western Sahara',
        'ER'=>'Eritrea',
        'ES'=>'Spain',
        'ET'=>'Ethiopia',
        'FI'=>'Finland',
        'FJ'=>'Fiji',
        'FK'=>'Falkland Islands (Malvinas)',
        'FM'=>'Micronesia (Federated States of)',
        'FO'=>'Faroe Islands',
        'FR'=>'France',
        'GA'=>'Gabon',
        'GB'=>'United Kingdom of Great Britain and Northern Ireland',
        'GD'=>'Grenada',
        'GE'=>'Georgia',
        'GF'=>'French Guiana',
        'GG'=>'Guernsey',
        'GH'=>'Ghana',
        'GI'=>'Gibraltar',
        'GL'=>'Greenland',
        'GM'=>'Gambia',
        'GN'=>'Guinea',
        'GP'=>'Guadeloupe',
        'GQ'=>'Equatorial Guinea',
        'GR'=>'Greece',
        'GS'=>'South Georgia and the South Sandwich Islands',
        'GT'=>'Guatemala',
        'GU'=>'Guam',
        'GW'=>'Guinea-Bissau',
        'GY'=>'Guyana',
        'HK'=>'Hong Kong',
        'HM'=>'Heard Island and McDonald Islands',
        'HN'=>'Honduras',
        'HR'=>'Croatia',
        'HT'=>'Haiti',
        'HU'=>'Hungary',
        'ID'=>'Indonesia',
        'IE'=>'Ireland',
        'IL'=>'Israel',
        'IM'=>'Isle of Man',
        'IN'=>'India',
        'IO'=>'British Indian Ocean Territory',
        'IQ'=>'Iraq',
        'IR'=>'Iran (Islamic Republic of)',
        'IS'=>'Iceland',
        'IT'=>'Italy',
        'JE'=>'Jersey',
        'JM'=>'Jamaica',
        'JO'=>'Jordan',
        'JP'=>'Japan',
        'KE'=>'Kenya',
        'KG'=>'Kyrgyzstan',
        'KH'=>'Cambodia',
        'KI'=>'Kiribati',
        'KM'=>'Comoros',
        'KN'=>'Saint Kitts and Nevis',
        'KP'=>'Korea (Democratic Peoples Republic of)',
        'KR'=>'Korea Republic of',
        'KW'=>'Kuwait',
        'KY'=>'Cayman Islands',
        'KZ'=>'Kazakhstan',
        'LA'=>'Lao Peoples Democratic Republic',
        'LB'=>'Lebanon',
        'LC'=>'Saint Lucia',
        'LI'=>'Liechtenstein',
        'LK'=>'Sri Lanka',
        'LR'=>'Liberia',
        'LS'=>'Lesotho',
        'LT'=>'Lithuania',
        'LU'=>'Luxembourg',
        'LV'=>'Latvia',
        'LY'=>'Libya',
        'MA'=>'Morocco',
        'MC'=>'Monaco',
        'MD'=>'Moldova Republic of',
        'ME'=>'Montenegro',
        'MF'=>'Saint Martin (French part)',
        'MG'=>'Madagascar',
        'MH'=>'Marshall Islands',
        'MK'=>'North Macedonia',
        'ML'=>'Mali',
        'MM'=>'Myanmar',
        'MN'=>'Mongolia',
        'MO'=>'Macao',
        'MP'=>'Northern Mariana Islands',
        'MQ'=>'Martinique',
        'MR'=>'Mauritania',
        'MS'=>'Montserrat',
        'MT'=>'Malta',
        'MU'=>'Mauritius',
        'MV'=>'Maldives',
        'MW'=>'Malawi',
        'MX'=>'Mexico',
        'MY'=>'Malaysia',
        'MZ'=>'Mozambique',
        'NA'=>'Namibia',
        'NC'=>'New Caledonia',
        'NE'=>'Niger',
        'NF'=>'Norfolk Island',
        'NG'=>'Nigeria',
        'NI'=>'Nicaragua',
        'NL'=>'Netherlands',
        'NO'=>'Norway',
        'NP'=>'Nepal',
        'NR'=>'Nauru',
        'NU'=>'Niue',
        'NZ'=>'New Zealand',
        'OM'=>'Oman',
        'PA'=>'Panama',
        'PE'=>'Peru',
        'PF'=>'French Polynesia',
        'PG'=>'Papua New Guinea',
        'PH'=>'Philippines',
        'PK'=>'Pakistan',
        'PL'=>'Poland',
        'PM'=>'Saint Pierre and Miquelon',
        'PN'=>'Pitcairn',
        'PR'=>'Puerto Rico',
        'PS'=>'Palestine State of',
        'PT'=>'Portugal',
        'PW'=>'Palau',
        'PY'=>'Paraguay',
        'QA'=>'Qatar',
        'RE'=>'Reunion',
        'RO'=>'Romania',
        'RS'=>'Serbia',
        'RU'=>'Russian Federation',
        'RW'=>'Rwanda',
        'SA'=>'Saudi Arabia',
        'SB'=>'Solomon Islands',
        'SC'=>'Seychelles',
        'SD'=>'Sudan',
        'SE'=>'Sweden',
        'SG'=>'Singapore',
        'SH'=>'Saint Helena Ascension and Tristan da Cunha',
        'SI'=>'Slovenia',
        'SJ'=>'Svalbard and Jan Mayen',
        'SK'=>'Slovakia',
        'SL'=>'Sierra Leone',
        'SM'=>'San Marino',
        'SN'=>'Senegal',
        'SO'=>'Somalia',
        'SR'=>'Suriname',
        'SS'=>'South Sudan',
        'ST'=>'Sao Tome and Principe',
        'SV'=>'El Salvador',
        'SX'=>'Sint Maarten (Dutch part)',
        'SY'=>'Syrian Arab Republic',
        'SZ'=>'Eswatini',
        'TC'=>'Turks and Caicos Islands',
        'TD'=>'Chad',
        'TF'=>'French Southern Territories',
        'TG'=>'Togo',
        'TH'=>'Thailand',
        'TJ'=>'Tajikistan',
        'TK'=>'Tokelau',
        'TL'=>'Timor-Leste',
        'TM'=>'Turkmenistan',
        'TN'=>'Tunisia',
        'TO'=>'Tonga',
        'TR'=>'Turkey',
        'TT'=>'Trinidad and Tobago',
        'TV'=>'Tuvalu',
        'TW'=>'Taiwan Province of China',
        'TZ'=>'Tanzania United Republic of',
        'UA'=>'Ukraine',
        'UG'=>'Uganda',
        'UM'=>'United States Minor Outlying Islands',
        'US'=>'United States of America',
        'UY'=>'Uruguay',
        'UZ'=>'Uzbekistan',
        'VA'=>'Holy See',
        'VC'=>'Saint Vincent and the Grenadines',
        'VE'=>'Venezuela (Bolivarian Republic of)',
        'VG'=>'Virgin Islands (British)',
        'VI'=>'Virgin Islands (U.S.)',
        'VN'=>'Viet Nam',
        'VU'=>'Vanuatu',
        'WF'=>'Wallis and Futuna',
        'WS'=>'Samoa',
        'YE'=>'Yemen',
        'YT'=>'Mayotte',
        'ZA'=>'South Africa',
        'ZM'=>'Zambia',
        'ZW'=>'Zimbabwe',
    ],
];